"""empty message

Revision ID: 4934fbfb1720
Revises: 
Create Date: 2024-02-29 15:25:59.250252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4934fbfb1720'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('usr_id', sa.UUID(), nullable=False),
    sa.Column('usr_username', sa.String(), nullable=True),
    sa.Column('usr_password', sa.String(), nullable=True),
    sa.Column('usr_email', sa.String(), nullable=True),
    sa.Column('usr_date_naissance', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('usr_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
